#!/usr/bin/env groovy

pipeline {
    agent {
        docker {
            image 'node-with-ssh-client'
        }
    }
    stages {
        stage('wohooo') {
            steps {
                // git@github.com:signed/connect-four.git
                sh 'ssh-keyscan -H github.com >> ~/.ssh/known_hosts'
                echo "Hello you"
            }
        }
    }
}
