version: '3'
services:
  jira:
    image: "dchevell/jira-core"
    ports:
      - "8081:8080"
    volumes:
      - ./var/jira:/var/atlassian/application-data/jira
  gogs:
    image: "gogs/gogs:0.11.86"
    ports:
     - "10022:22"
     - "10080:3000"
    volumes:
     - ./var/gogs:/data
  jenkins:
    build:
      context: .
      dockerfile: JenkinsWithDocker
    ports:
     - "8080:8080"
     - "50000:50000"
    volumes:
     - ./var/jenkins:/var/jenkins_home
     - /var/run/docker.sock:/var/run/docker.sock