pipeline {
    agent { docker { image 'maven:3.5.4' } }
    stages {
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('test') {
            steps {
                sh 'cd jenkinsfile && mvn test'
                junit('**/target/**/*.xml')
                sh 'echo "output" > result.txt'
                archiveArtifacts artifacts: '*.txt', fingerprint: true
            }
        }
    }
}