pipeline {
    agent { docker { image 'primed_with_maven' } }

    options {
        disableConcurrentBuilds()
        timestamps()
    }

    stages {
        stage('the parallel quest') {
            failFast true
            parallel {
                stage('one') {
                    steps {
                        echo "one"
                    }
                }
                stage('two') {
                    steps {
                        echo "two"
                    }
                }
            }
        }
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('test') {
            steps {
                sh 'cd jenkinsfile && mvn test'
                sh 'echo "output" > result.txt'
                archiveArtifacts artifacts: '*.txt', fingerprint: true
            }
            post {
                always {
                    junit '**/target/*-reports/TEST-*.xml'
                }

            }
        }
    }
}