pipeline {
    agent { docker { image 'primed_with_maven' } }

    options {
        disableConcurrentBuilds()
        timestamps()
    }

    parameters {
        string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
    }

    stages {
        stage('the parallel quest') {
            failFast true
            parallel {
                stage('access parameters') {
                    steps {
                        echo "Hello ${params.PERSON}"
                    }
                }
                stage('two') {
                    steps {
                        echo "two"
                        script {
                            currentBuild.displayName = 'displayName from pipeline'
                            currentBuild.description = 'description from pipeline'
                        }
                    }
                }
            }
        }
        stage('build') {
            steps {
                sh 'mvn --version'
            }
        }
        stage('test') {
            steps {
                sh 'cd jenkinsfile && mvn test'
                sh 'echo "output" > result.txt'
                archiveArtifacts artifacts: '*.txt', fingerprint: true
            }
            post {
                always {
                    junit '**/target/*-reports/TEST-*.xml'
                }

            }
        }
    }
}